# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf48299395c14abce51a671ff49f9d940a7e915927e2b2862b614533e3993e800513390ccc5c368e77203336836fd887f70da92aa8455c3e14a581586682485

test:
  secret_key_base: 7b9c1e4f4d54c894fccfa36e86988c949c5e27d8d45b199a69e09b47857fda0be78cb21bf42d3621081724dfe6dc0fb44c8fe7d92c8929eb7558c0f5fb8a47f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
